"""empty message

Revision ID: cd87a4e60bda
Revises: 61524a7ec198
Create Date: 2018-08-09 21:21:00.928444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd87a4e60bda'
down_revision = '61524a7ec198'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=250), nullable=True),
    sa.Column('votes', sa.Integer(), nullable=True),
    sa.Column('posttime', sa.DateTime(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_body'), 'comment', ['body'], unique=False)
    op.add_column('post', sa.Column('posttime', sa.DateTime(), nullable=True))
    op.add_column('post', sa.Column('votes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'votes')
    op.drop_column('post', 'posttime')
    op.drop_index(op.f('ix_comment_body'), table_name='comment')
    op.drop_table('comment')
    # ### end Alembic commands ###
